### ISSUE TITLE
Use Heavy Ammo/Go to Public Events?

### ISSUE THREAD

**Issue by mew351** [LenAnderson/DestinyRPG-Bot#5]
Hey! I'm really loving the script, currently level 96, I was wondering if it'd be possible to have us use heavy ammo for most attacks? I have over 20k heavy ammo and am thinking that it might be nice to use it since it does a bit more damage :)

Any possibility of having it go to public events and then going back to the spot you were grinding?
I understand you're not being paid or anything and it's just a side project but still, thank you for all your hard work!

**Comment by LenAnderson** [comment]
I'm in the same boat right now. Heavy ammo is plenty, so I'm going to add using it on all enemies as an option.

I also thought about automating PEs. Unfortunately they are back to being rare which makes developing this feature a little tedious... But it's on my list.

**Comment by mew351** [comment]
Okay!
Thanks so much dude!

**Comment by mew351** [comment]
Oh yeah! Also to use your ultimate ability, like Golden Gun or something 





On Fri, Aug 18, 2017 4:32 AM, Len notifications@github.com  wrote:
I'm in the same boat right now. Heavy ammo is plenty, so I'm going to add using
it on all enemies as an option.

I also thought about automating PEs. Unfortunately they are back to being rare
which makes developing this feature a little tedious... But it's on my list.

**Comment by LenAnderson** [comment]
An option for heavy/super attack is now in. PEs are complicated to detect properly. I am not going to spend time on this before Alpha2. There's probably going to be a lot of bot-breaking changes anyways...
