### ISSUE TITLE
Some notes and minor fixes

### ISSUE THREAD

**Issue by zenikin** [LenAnderson/DestinyRPG-Bot#7]
I've been tinkering with this since last night in the wake of Alpha2. It looks like you've already noticed they split the "run" link into "runlink" and "patrollink". I've also discovered they've changed the "disabled" flag in some way; if you remove the check for disabled targets, the bot no longer stalls or refreshes the target list while trying to selecting a target. Still not sure why it's activating all the targets (at least visually). Another issue I've noticed that I have not been able to fix is that sometimes after death, the bot will return to Tower Patrol instead of the last area it was in. This seems to happen during rapid death/respawn cycles.

**Comment by zenikin** [comment]
I've just noticed another issue, could be a result of my changes to "disabled" targets. Once the area is empty (no targets), the bot gets stuck and doesn't activate the "nothinglink".

**Comment by LenAnderson** [comment]
Cool. I'll check it out after the weekend.

**Comment by zenikin** [comment]
Just an update, I figured out a couple things. The thing where it visually appears to select all targets isn't related to the bot, it's just how the game is now. As for the "disabled" targets, it seems like a lot of enemies are flagged as "disabled" now despite being in the list. However, when no targets are left in an area, there is one hidden enemy with no ID that is also flagged as "disabled". This means either you avoid the "disabled" enemies and get the bot skipping a lot of enemies, or you removed the "disabled" filter and the bot gets stuck once an area is empty. I haven't found a way around this yet.

**Comment by zenikin** [comment]
I fixed the bot getting stuck when there are no enemies left. Comment out the "disabled" filter line, and add this line under it:
`if (t.el.getAttribute('data-enemyguid') == '') return false;`
